### ISSUE TITLE
Cannot read properties of undefined (reading 'default')

### ISSUE THREAD

**Issue by krunaldodiya** [Louxsdon/django-breeze#6]
**Describe the bug**
```
createInertiaApp.ts:34 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'default')
    at createInertiaApp.ts:34:93
    at async j2 (createInertiaApp.ts:38:18)
```

**To Reproduce**
1. when running python manage.py runserver

**Expected behavior**
It should show hompage without any warnings

**Screenshots**

**Desktop (please complete the following information):**
 - Pop OS / linux
 - google chrome

**Additional context**
![Screenshot from 2023-12-01 15-09-35](https://github.com/Louxsdon/django-breeze/assets/7272013/8fcd1962-8cea-4a3f-84b0-31941ad316e8)

**Comment by krunaldodiya** [comment]
Sorry, Found out the issue is with naming case sensitivity instead of index, i wrote Index

```
from inertia import render


# Create your views here.
def home(request):
    return render(request, "index")
```
